// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: SelectUserIdFromEmail.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const userIdFromEmail = `-- name: UserIdFromEmail :one
SELECT id FROM users
WHERE email = $1
`

func (q *Queries) UserIdFromEmail(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, userIdFromEmail, email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
